build:
  image: maven:3.3.3-jdk-8-onbuild
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
    - SCALA_VERSION=2.10.6
  commands:
    - git log | head -n 20
    - mvn clean install -Dgpg.skip=true
    - if [ -z "CI_PULL_REQUEST" ] ; then
        mvn deploy -s .settings.xml -Dgpg.skip=true;
      fi
